Added escape_html utility function # PM-3462
IMIO/Products.PloneMeeting pull request #105
Opened 2021-06-30 13:00 UTC by odelaere

2021-06-30 13:20 UTC, gbastien requested changes
À déplacer dans utils.py

2021-06-30 13:20 UTC, gbastien commented on src/Products/PloneMeeting/ToolPloneMeeting.py
> +    security.declarePublic('escape_html')
@odelaere ce genre de fonction plus "bas niveau" je les mets plutôt dans "utils".

Tu peux la nommer juste "escape" car çà pourrait être utilisé dans d'autres cas que du HTML...

2021-06-30 13:20 UTC, gbastien commented on src/Products/PloneMeeting/ToolPloneMeeting.py
> +import cgi
Attention les import qui commencent par "import ..." sont mis en dessous des autres imports...

2021-06-30 13:21 UTC, odelaere commented on src/Products/PloneMeeting/ToolPloneMeeting.py
> +import cgi
y a pas isort dans les pre-commit ?

2021-07-01 09:34 UTC, gbastien commented on CHANGES.rst
> +- Added escape_html utility function # PM-3462 .
@odelaere Added utils.escape ... et tu peux merger

2021-07-01 09:51 UTC, merged