PM-4147: print_attendees_by_type improvements to handle in and out counts
IMIO/Products.PloneMeeting pull request #256
Opened 2024-01-05 14:51 UTC by duchenean

2024-01-05 15:40 UTC, duchenean commented
See 25, 26 and 27 in this template :
[attendees.odt](https://github.com/IMIO/Products.PloneMeeting/files/13843871/attendees.odt)

If this is OK, I'll update the one in https://github.com/IMIO/Products.MeetingCommunes

2024-01-22 08:14 UTC, gbastien requested changes

2024-01-23 14:40 UTC, duchenean commented on src/Products/PloneMeeting/browser/views.py
> +                if include_in_count and len(not_present_item_uids) > 0:
@gbastien Merci, j'ai corrigé (et ajouté une ligne au changelog).
Je merge. J'ai préparé une suite (branche PM-4147-2) pour rendre ça plus configurable mais ce n'est pas encore prêt.

2024-01-23 14:40 UTC, merged

2024-01-23 14:42 UTC, duchenean commented on src/Products/PloneMeeting/browser/views.py
> +                if include_in_count and len(not_present_item_uids) > 0:
Ici #257